
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service/", className = "proxy.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service/", className = "proxy.GetComptesResponse")
    @Action(input = "http://service/BanqueService/getComptesRequest", output = "http://service/BanqueService/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param montant
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service/", className = "proxy.GetCompteResponse")
    @Action(input = "http://service/BanqueService/getCompteRequest", output = "http://service/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns proxy.BanqueService_Type
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBanqueServicePort", targetNamespace = "http://service/", className = "proxy.GetBanqueServicePort")
    @ResponseWrapper(localName = "getBanqueServicePortResponse", targetNamespace = "http://service/", className = "proxy.GetBanqueServicePortResponse")
    @Action(input = "http://service/BanqueService/getBanqueServicePortRequest", output = "http://service/BanqueService/getBanqueServicePortResponse")
    public BanqueService_Type getBanqueServicePort();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://service/", className = "proxy.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://service/", className = "proxy.ConversionResponse")
    @Action(input = "http://service/BanqueService/conversionRequest", output = "http://service/BanqueService/conversionResponse")
    public double conversion(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
